name: Maven Package

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose browser: chrome, edge, firefox'
        required: true
        default: 'chrome'
      suite:
        description: 'Choose automation suite: RegressionSuite, FeaturesSuite'
        required: true
        default: 'RegressionSuite'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      chrome:
        image: selenium/node-chrome
        options: --shm-size=2gb
        ports:
          - "5900"
        env:
          SE_EVENT_BUS_HOST: localhost
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_NODE_GRID_URL: http://localhost:4444
          SE_NODE_MAX_SESSIONS: 20
          SE_NODE_SESSION_TIMEOUT: 180
          SE_NODE_OVERRIDE_MAX_SESSIONS: TRUE
          START_XVFB: false
      edge:
        image: selenium/node-edge
        options: --shm-size=2gb
        ports:
          - "5901"
        env:
          SE_EVENT_BUS_HOST: localhost
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_NODE_GRID_URL: http://localhost:4444
          SE_NODE_MAX_SESSIONS: 20
          SE_NODE_SESSION_TIMEOUT: 180
          SE_NODE_OVERRIDE_MAX_SESSIONS: TRUE
          START_XVFB: false

    steps:
      - uses: actions/checkout@v3

      - name: Clear old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days # Set this to 0 to delete all artifacts

      - name: Set up JDK 11
        env:
          ACTIONS_RUNNER_DEBUG: true
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Run SQL file
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -proot < itSchoolDBQueries.sql

      - name: Run tests
        run: mvn clean install -Dci_cd=true -Dbrowser=${{ github.event.inputs.browser }} -DsuiteXmlFile=suites/${{ github.event.inputs.suite }} -PCustomSuite

      - name: Publish regression logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: RegressionLogs
          path: target/logs/RegressionLogs.log

      - name: Publish html report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ExtentReport
          path: target/extentReports
